CREATE DATABASE FERIAVIRTUAL

CREATE TABLE REGISTRO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    CEDULA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN
)


CREATE TABLE ADMIN(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO1 VARCHAR(200) NOT NULL,
    APELLIDO2 VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    CEDULA VARCHAR(200) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN
) 