CREATE TABLE REGISTRO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL UNIQUE,
    CEDULA VARCHAR(200) NOT NULL UNIQUE,
    ESTADO BOOLEAN
);


CREATE TABLE ADMIN(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN
); 
