CREATE DATABASE FERIAVIRTUAL

CREATE TABLE REGISTRO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    CEDULA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN
<<<<<<< HEAD
)


CREATE TABLE ADMIN(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDO1 VARCHAR(200) NOT NULL,
    APELLIDO2 VARCHAR(200) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    CEDULA VARCHAR(200) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL,
    ESTADO BOOLEAN
) 
=======
);
-- asdf cc
>>>>>>> 989c58b1d1810c4eabfc95473afce06b0964b0e7
